### ISSUE TITLE
Incorrect Combinations with repetitions

### ISSUE THREAD

**Issue by adrianwalker** [dpaukov/combinatoricslib3-example#1]
For version 3.1.0 downloaded using maven:

```
<dependency>
  <groupId>com.github.dpaukov</groupId>
  <artifactId>combinatoricslib3</artifactId>
  <version>3.1.0</version>
</dependency>
```

The combinations with repetitions example code gives the wrong output:

Generator.combination(new String[]{"apple", "orange"})
            .multi(3)
            .stream()
            .forEach(System.out::println);

Outputs:

[apple, apple, apple]
[apple, apple, orange, apple, apple, apple]
[apple, orange, orange, apple, apple, orange, apple, apple, apple]
[orange, orange, orange, apple, orange, orange, apple, apple, orange, apple, apple, apple]

For java version:

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by dpaukov** [comment]
Hello Adrian,

Thank you for submitting this bug. It is fixed in the latest release version 3.1.1.

```
<dependency>
  <groupId>com.github.dpaukov</groupId>
  <artifactId>combinatoricslib3</artifactId>
  <version>3.1.1</version>
</dependency>
```
